In [13]:
import re
from typing import List, Any

import numpy as np
import pandas as pd

In [2]:
class InvalidFormatError(Exception):
    pass


def pipe(raw_input: Any, *functions: Any, **functions_with_args: Any) -> Any:

    output = raw_input

    if functions:
        for function in functions:
            output = function(output)

    if functions_with_args:
        for function, args_list in functions_with_args.items():
            output = eval(function)(output, *args_list)

    return output


def _clean_states(text: str) -> List[str]:
    return text.strip('][').strip().replace('\n', '')   


def _format_whitespaces(text: str) -> List[str]:
    return re.sub(' {2,}', ' ', text).split()


def _evaluate_states(states: List[str]) -> List[float]:
    return [eval(state) for state in states]


def _format_states(states: str) -> List[str]:
    return pipe(
        states,
        _clean_states,
        _format_whitespaces,
        _evaluate_states
    )


def format_states(df: pd.DataFrame) -> pd.DataFrame:
    if df.shape[0] == 1:
        return df.T[0].apply(_format_states).apply(pd.Series)
    else:
        try:
            return df[0].apply(_format_states).apply(pd.Series)
        except Exception:
            raise InvalidFormatError("Invalid DataFrame format")

In [3]:
path = '/Users/d.e.magno/Temporary/playground/py/epi-rl/states.csv'

In [4]:
df = pd.read_csv(path, header=None)

In [7]:
df_states = format_states(df)

In [11]:
df_states

0         1         2         3             4             5   \
0   0.128028  0.268238  0.999950  0.159630  0.000000e+00  2.441330e-05   
1   0.128011  0.267900  0.999748  0.159624  5.005097e-07  7.528829e-05   
2   0.127936  0.266611  0.998600  0.159546  2.901063e-05  3.272127e-04   
3   0.127358  0.259969  0.992450  0.159187  1.314112e-04  1.621365e-03   
4   0.125588  0.253630  0.977786  0.158279  3.151500e-04  9.619491e-04   
5   0.122908  0.227698  0.947062  0.156421  6.060100e-04  6.272547e-03   
6   0.115631  0.157828  0.859842  0.150377  1.297330e-03  1.159764e-02   
7   0.104052  0.130206  0.751393  0.142748  1.457690e-03  2.548900e-03   
8   0.097691  0.105310  0.683724  0.137068  7.587900e-04  2.892270e-03   
9   0.093894  0.089305  0.640434  0.133173  5.370386e-04  1.705630e-03   
10  0.091734  0.082205  0.618799  0.131115  2.327053e-04  7.710827e-04   
11  0.090666  0.078932  0.608109  0.130102  1.618182e-04  3.056258e-04   
12  0.090223  0.077508  0.602773  0.129712  5.051200e-05  1.261523e-04   
13  0.089949  0.076981  0.600014  0.129459  1.883012e-05  3.041761e-05   
14  0.089812  0.076829  0.598875  0.129344  7.189263e-06  1.249499e-05   
15  0.089778  0.076758  0.598380  0.129314  5.946745e-06  2.240143e-05   
16  0.089758  0.076714  0.598267  0.129302  2.356634e-06  2.799119e-06   
17  0.089740  0.076697  0.598233  0.129294  1.080322e-06  0.000000e+00   
18  0.089740  0.076691  0.598200  0.129289  1.039411e-06  1.567108e-06   
19  0.089726  0.076691  0.598130  0.129279  0.000000e+00  2.604524e-06   
20  0.089712  0.076645  0.598095  0.129266  1.657924e-06  1.784200e-05   
21  0.089694  0.076628  0.598056  0.129261  6.650149e-06  2.870325e-06   
22  0.089678  0.076613  0.598017  0.129260  1.961360e-07  0.000000e+00   
23  0.089667  0.076601  0.597961  0.129257  1.507912e-06  9.001146e-07   
24  0.089652  0.076575  0.597918  0.129267  4.293181e-06  6.253239e-06   
25  0.089650  0.076564  0.597814  0.129262  1.318725e-06  2.268068e-06   
26  0.089640  0.076507  0.597696  0.129244  4.117115e-07  5.210121e-06   
27  0.089618  0.076477  0.597564  0.129219  3.750736e-07  0.000000e+00   
28  0.089603  0.076467  0.597443  0.129217  3.845039e-06  3.248702e-06   
29  0.089596  0.076461  0.597407  0.129221  0.000000e+00  2.571639e-06   
30  0.089599  0.076471  0.597402  0.129220  0.000000e+00  0.000000e+00   
31  0.089592  0.076455  0.597381  0.129217  2.890514e-07  3.733665e-06   
32  0.089584  0.076450  0.597345  0.129210  0.000000e+00  0.000000e+00   
33  0.089580  0.076442  0.597303  0.129195  3.083933e-07  3.215548e-06   
34  0.089571  0.076413  0.597217  0.129184  0.000000e+00  0.000000e+00   
35  0.089573  0.076411  0.597183  0.129179  4.014310e-07  1.591587e-06   
36  0.089574  0.076406  0.597167  0.129180  0.000000e+00  0.000000e+00   
37  0.089560  0.076400  0.597140  0.129183  2.442715e-06  8.341939e-07   
38  0.089550  0.076388  0.597093  0.129183  9.457962e-07  1.343290e-06   
39  0.089524  0.076353  0.596975  0.129176  4.750005e-06  2.851198e-06   
40  0.089517  0.076358  0.596933  0.129171  3.363639e-06  2.833177e-06   
41  0.089505  0.076340  0.596884  0.129166  4.762528e-07  2.880400e-06   
42  0.089492  0.076341  0.596860  0.129162  3.910626e-06  6.674068e-07   

              6             7             8             9         10  \
0   2.801172e-05  5.083611e-06  1.075038e-05  5.834197e-05  0.000009   
1   1.217185e-04  1.636435e-05  3.781568e-06  9.039120e-05  0.000006   
2   3.010867e-04  1.363446e-05  1.585567e-05  4.117051e-04  0.000345   
3   1.411227e-03  1.080535e-04  1.319772e-04  2.031826e-03  0.001948   
4   2.262955e-03  1.528161e-04  4.560462e-04  1.652298e-03  0.004051   
5   6.182200e-03  2.659699e-04  7.863169e-04  7.843621e-03  0.009266   
6   1.691418e-02  1.211200e-03  2.115110e-03  1.971497e-02  0.025397   
7   1.248247e-02  9.807800e-04  2.969530e-03  6.283700e-03  0.026197   
8   8.127520e-03  7.676300e-04  1.553330e-03  6.367350e-03  0.015870   
9   4.537154e-03  4.450802e-04  8

In [19]:
X = df_states.loc[0].values

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [32]:
sample = df_states.loc[0].values

In [28]:
scaler = MinMaxScaler()

In [30]:
scaler.fit_transform(sample)

ValueError: Expected 2D array, got 1D array instead:
array=[1.2802751e-01 2.6823780e-01 9.9995005e-01 1.5963008e-01 0.0000000e+00
 2.4413304e-05 2.8011716e-05 5.0836106e-06 1.0750377e-05 5.8341968e-05
 9.4452289e-06 1.1353458e-06 1.4163737e-06 2.6346688e-05 1.9905863e-05
 6.8979593e-06 1.0000000e+00].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [36]:
sample.reshape(1, -1).shape

(1, 17)

In [42]:
scaler.fit_transform(sample.reshape(1, -1))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]])

In [43]:
scaler.fit_transform(sample.reshape(-1, 1))

array([[1.2802751e-01],
       [2.6823780e-01],
       [9.9995005e-01],
       [1.5963008e-01],
       [0.0000000e+00],
       [2.4413304e-05],
       [2.8011716e-05],
       [5.0836106e-06],
       [1.0750377e-05],
       [5.8341968e-05],
       [9.4452289e-06],
       [1.1353458e-06],
       [1.4163737e-06],
       [2.6346688e-05],
       [1.9905863e-05],
       [6.8979593e-06],
       [1.0000000e+00]])

In [63]:
sample

array([1.2802751e-01, 2.6823780e-01, 9.9995005e-01, 1.5963008e-01,
       0.0000000e+00, 2.4413304e-05, 2.8011716e-05, 5.0836106e-06,
       1.0750377e-05, 5.8341968e-05, 9.4452289e-06, 1.1353458e-06,
       1.4163737e-06, 2.6346688e-05, 1.9905863e-05, 6.8979593e-06,
       1.0000000e+00])

In [66]:
scaler.inverse_transform(scale_states(sample))

array([[1.2802751e-01, 2.6823780e-01, 9.9995005e-01, 1.5963008e-01,
        0.0000000e+00, 2.4413304e-05, 2.8011716e-05, 5.0836106e-06,
        1.0750377e-05, 5.8341968e-05, 9.4452289e-06, 1.1353458e-06,
        1.4163737e-06, 2.6346688e-05, 1.9905863e-05, 6.8979593e-06,
        1.0000000e+00]])

In [48]:
def scale_states(states: np.ndarray) -> np.ndarray:
    return scaler.fit_transform(states.reshape(1, -1))

In [68]:
sample.shape

(17,)

In [67]:
scaler.inverse_transform(scale_states(sample)).shape

(1, 17)

In [53]:
array = np.array([1, 234234, 2342434, 3423234])

In [62]:
scaler.inverse_transform(scaler.fit_transform(df_states.values))

array([[1.28027510e-01, 2.68237800e-01, 9.99950050e-01, 1.59630080e-01,
        0.00000000e+00, 2.44133040e-05, 2.80117160e-05, 5.08361060e-06,
        1.07503770e-05, 5.83419680e-05, 9.44522890e-06, 1.13534580e-06,
        1.41637370e-06, 2.63466880e-05, 1.99058630e-05, 6.89795930e-06,
        1.00000000e+00],
       [1.28010526e-01, 2.67900437e-01, 9.99747694e-01, 1.59623682e-01,
        5.00509657e-07, 7.52882916e-05, 1.21718535e-04, 1.63643508e-05,
        3.78156824e-06, 9.03912005e-05, 5.77381479e-06, 0.00000000e+00,
        3.31555057e-05, 2.80770182e-04, 1.40012184e-04, 3.20374056e-05,
        1.00000000e+00],
       [1.27936010e-01, 2.66611370e-01, 9.98599530e-01, 1.59545870e-01,
        2.90106250e-05, 3.27212680e-04, 3.01086750e-04, 1.36344620e-05,
        1.58556670e-05, 4.11705110e-04, 3.44956260e-04, 2.58228960e-05,
        8.69302970e-05, 9.96609450e-04, 7.69629200e-04, 8.76154080e-05,
        1.00000000e+00],
       [1.27358350e-01, 2.59968940e-01, 9.92449940e-01, 1.591